---
# UFW Configuration

- name: My playbook
  hosts: all
  become: yes
  tasks:
  - name: Allow outgoing and enable UFW
    community.general.ufw:
      state: enabled
#      direction: outgoing
#      policy: allow

#  - name: Incoming deny
#    community.general.ufw:
#      state: enabled
#      direction: incoming
#      policy: deny

  - name: Set logging
    community.general.ufw:
      logging: 'on'

  - community.general.ufw:
      rule: reject
      port: auth
      log: true

  - community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: Delete OpenSSH rule
    community.general.ufw:
      rule: allow
      name: OpenSSH
      delete: true

  - community.general.ufw:
      rule: allow
      name: OpenSSH
      src: '{{ item }}'
    loop:
      - 10.12.0.0/16
      - 10.16.0.0/16

  - community.general.ufw:
      rule: allow
      port: 443

  - name: Allow all access from xcite networks to this host
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
    loop:
      - 10.233.70.0/24
      - 10.233.121.0/24
      - 10.233.0.0/16
      - 169.226.0.0/24
      - 203.0.113.0/24
      - 10.12.0.0/16
      - 10.16.0.0/16
      - 129.15.42.34
      - 129.15.42.0/23
      - 169.226.68.0/24
      - 10.223.17.0/24
      - 10.233.0.0/24

  - name: allow access for dec, UL upload, chge
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      port: '22'
    loop:
      - 173.233.79.128/26
      - 173.233.90.0/27
      - 64.72.84.99 
      - 134.179.252.122

  - name: allow access for dec, UL upload, CHGE
    community.general.ufw:
      rule: allow
      src: '{{ item }}'
      port: '49152'
    loop:
      - 173.233.79.128/26
      - 173.233.90.0/27
      - 134.179.252.122
      - 64.72.84.99

  - name: allow access for devtron
    community.general.ufw:
      rule: allow
      src: 10.233.17.47

  - name: allow out access on bond1
    community.general.ufw:
      rule: allow
      interface: bond1
      direction: out

  - name: allow in access on bond1 
    community.general.ufw:
      rule: allow
      interface: bond1
      direction: in
